# Generated by Django 5.1.1 on 2024-09-27 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='current_price',
            new_name='last_price',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='quantity',
            new_name='position',
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(choices=[('stock_us', 'US Stock'), ('stock_au', 'Aus Stock'), ('crypto', 'Cryptocurrency')], max_length=10),
        ),
    ]
