# Generated by Django 5.1.1 on 2024-09-27 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_rename_current_price_asset_last_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(choices=[('stock_us', 'US Stock'), ('stock_au', 'AUS Stock'), ('crypto', 'Cryptocurrency')], max_length=10),
        ),
    ]
