# Generated by Django 5.1.1 on 2024-09-28 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_asset_asset_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='sector',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
    ]
